name = "cloud-notepad"
main = "src/index.js"
compatibility_date = "2022-05-13"

kv_namespaces = [
  { binding = "NOTES", id = "f37d918aa717481ca182693227058bd2" },
  { binding = "SHARE", id = "7b9e107184d747f08331e427c50d90ef" }
]